// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdeNlPoB5KpbAsK_Ylkw7jJ2Zs6TpcK8o',
    appId: '1:692605394807:web:4a3f5487b162b937e3cb72',
    messagingSenderId: '692605394807',
    projectId: 'mindbox-3afe9',
    authDomain: 'mindbox-3afe9.firebaseapp.com',
    storageBucket: 'mindbox-3afe9.appspot.com',
    measurementId: 'G-JRG7N6BRBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Q_X2y1-ZqEA-6n_GvgZYSxv_frteNKk',
    appId: '1:692605394807:android:c099d96c18b524f9e3cb72',
    messagingSenderId: '692605394807',
    projectId: 'mindbox-3afe9',
    storageBucket: 'mindbox-3afe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD60HRu0TwlioDPzjcnKK4OrXMRVJbzUiA',
    appId: '1:692605394807:ios:f9fb507385c72c93e3cb72',
    messagingSenderId: '692605394807',
    projectId: 'mindbox-3afe9',
    storageBucket: 'mindbox-3afe9.appspot.com',
    iosBundleId: 'com.emreciftci.giftbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD60HRu0TwlioDPzjcnKK4OrXMRVJbzUiA',
    appId: '1:692605394807:ios:f9fb507385c72c93e3cb72',
    messagingSenderId: '692605394807',
    projectId: 'mindbox-3afe9',
    storageBucket: 'mindbox-3afe9.appspot.com',
    iosBundleId: 'com.emreciftci.giftbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdeNlPoB5KpbAsK_Ylkw7jJ2Zs6TpcK8o',
    appId: '1:692605394807:web:218c0935d3a7875ce3cb72',
    messagingSenderId: '692605394807',
    projectId: 'mindbox-3afe9',
    authDomain: 'mindbox-3afe9.firebaseapp.com',
    storageBucket: 'mindbox-3afe9.appspot.com',
    measurementId: 'G-BP1KSWK20N',
  );
}
